# Generated by Django 5.1.6 on 2025-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cv_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
