# Generated by Django 5.1.6 on 2025-02-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lien',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
