# Generated by Django 5.1.6 on 2025-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_event_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
