# Generated by Django 5.1.6 on 2025-02-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_notification_cv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
