# Generated by Django 5.1.4 on 2025-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
