# Generated by Django 5.1.6 on 2025-02-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0003_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunities',
            name='domaine',
            field=models.CharField(default='dev', max_length=20),
        ),
    ]
