# Generated by Django 5.1.6 on 2025-02-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_opportunities_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bdd.user')),
                ('resp_one', models.CharField(default='idk', max_length=20)),
                ('resp_two', models.CharField(default='idk', max_length=20)),
                ('resp_three', models.CharField(default='idk', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='domaine',
            new_name='role',
        ),
    ]
