# Generated by Django 5.1.4 on 2025-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0005_alter_quest_resp_one_alter_quest_resp_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='resp_one',
            field=models.TextField(default='I want to gain practical experience in my field, develop my skills, and learn from professionals in a real work environment.'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='resp_three',
            field=models.TextField(default='I hope to gain hands-on experience, improve my technical and soft skills, and learn from industryprofessionals to prepare for my future career.'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='resp_two',
            field=models.TextField(default='I admire your companys work in tech field , and this role aligns perfectly with my skills and career goals. I’m excited about the opportunity to contribute and learn.'),
        ),
    ]
