# Generated by Django 5.1.6 on 2025-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0005_quest_rename_domaine_experience_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
